#!/usr/bin/env python3

import sys, os, string

pythonlibs = '{}/../lib/python'.format(os.path.dirname(sys.argv[0]))
sys.path.append(pythonlibs)

import ds_opts

import ds_summary
import ds_normalize
import ds_flatten
import ds_pack
import ds_check



if sys.version_info[0] < 3:
    print("requires python version 3.0 or later")
    exit()

options = ds_opts.process_args()

if (options['mode'] == "summary"):
    ds_summary.execute_summary(options['targets'])
elif (options['mode'] == "normalize"):
    ds_normalize.execute_normalize(options['targets'], verbose=options['verbose'], recursive=options['recursive'])
elif (options['mode'] == "flatten-links"):
    ds_flatten.execute_flatten(options['targets'], verbose=options['verbose'], recursive=options['recursive'])
elif (options['mode'] == "pack"):
    ds_pack.execute_pack(options['targets'], verbose=options['verbose'])
elif (options['mode'] == "check"):
    ds_check.execute_check(options['targets'])
