#!/usr/bin/env python3



import sys, os, string

pythonlibs = '{}/../lib/python'.format(os.path.dirname(sys.argv[0]))
sys.path.append(pythonlibs)

import dsdocs
import dssummary



prog = os.path.basename(sys.argv[0])
if sys.version_info[0] < 3:
    print("requires python version 3.0 or later")
    exit()
if (len(sys.argv) == 1):
    dsdocs.show_usage(prog, "")
    sys.exit(0)
mode = sys.argv[1]
modeargs = sys.argv
del modeargs[0]
del modeargs[0]


if (mode == "summary"):
    if (len(modeargs) != 0):
        for loc in modeargs:
            dssummary.summary(loc)
    else:
        print("no targets specified")
else:
    dsdocs.show_usage(prog, "mode '{}' not recognized".format(mode))
