#!/usr/bin/env perl
########################################################################
# ds-replace-symlink
########################################################################
# Usage:
#     ds-replace-symlink <linkfile> [...]
########################################################################


use strict;
use warnings;

use Data::Dumper;
use File::Basename;
use FindBin;


use lib "$FindBin::Bin/lib";

use DS;


########################################################################
foreach my $linkfile (@ARGV) {
    replace_symlink($linkfile)
}

########################################################################
0;
